### ISSUE TITLE
Upgrade this template to slick 2.x

### ISSUE THREAD

**Issue by jarl-dk** [typesafehub/activator-hello-play#22]
I have tried to upgrade this to slick 2.x, but I run into problems.

I have used this diff to upgrade (obeying the version matrix on https://github.com/playframework/play-slick):

``` diff
diff --git a/build.sbt b/build.sbt
index 0303f23..63f4894 100644
--- a/build.sbt
+++ b/build.sbt
@@ -22,6 +22,6 @@ libraryDependencies ++= Seq(

 play.Project.playScalaSettings

-libraryDependencies += "com.typesafe.slick" %% "slick" % "1.0.1"
+libraryDependencies += "com.typesafe.slick" %% "slick" % "2.0.3"

-libraryDependencies += "com.typesafe.play" %% "play-slick" % "0.5.0.2-SNAPSHOT"
+libraryDependencies += "com.typesafe.play" %% "play-slick" % "0.7.0"
```

But When doing `activator run` I get this output

```
$ activator run
[info] Loading project definition from /home/jarl/projects/heartreacher/activator-play-slick/project
[info] Set current project to hello-play (in build file:/home/jarl/projects/heartreacher/activator-play-slick/)

java.lang.NoSuchMethodException: play.core.server.NettyServer.mainDevHttpMode(play.core.SBTLink, play.core.SBTDocHandler, int)
        at java.lang.Class.getMethod(Class.java:1670)
        at play.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$1.apply(PlayRun.scala:232)
        at play.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$1.apply(PlayRun.scala:91)
        at scala.Function7$$anonfun$tupled$1.apply(Function7.scala:35)
        at scala.Function7$$anonfun$tupled$1.apply(Function7.scala:34)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
[trace] Stack trace suppressed: run last compile:run for the full output.
[error] (compile:run) java.lang.NoSuchMethodException: play.core.server.NettyServer.mainDevHttpMode(play.core.SBTLink, play.core.SBTDocHandler, int)
[error] Total time: 1 s, completed 14-01-2015 10:48:38
```

It would be really nice if this template was updated to slick 2.1

**Comment by jarl-dk** [comment]
Sorry. Wrong repo: I was intended to hit https://github.com/mkelland/activator-play-slick
